# -*- coding: utf-8 -*-
"""Third year Eng. Students work1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UlsTe8uzcb2IxL44bseFBjsI451vr6s0
"""

print ("Hello, Worlds")

print("I","Love","Python")



name = input("Enter your name: ")
age = input("Enter your age: ")
course = input("Enter your course: ")
cgpa = input("Enter your CGPA: ")

print(f"\nStudent Info:\nName: {name}\nAge: {age}\nCourse: {course}\nCGPA: {cgpa}")



