# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1auO5nSehd-q-ANuALkLy8xNv8fdbe8Vz
"""

# ----- Lists -----
print("=== LIST Example ===")
my_list = [10, 20, 30]
print("Original list:", my_list)

my_list.append(40)   # add an item
my_list[1] = 25      # change an item
print("Updated list:", my_list)